#!/bin/bash
#git add *
cat LESMEG.txt > README
echo "Oppgi kommentar til commit"
read comment
git commit -am "$comment"
git push origin master
# github oppdatert
cp -R * /Users/howl/www/prosjekt/
# backup opprettet
# sender ny versjon til gremlin
scp -r * oivindoh@gremlin.stud.aitel.hist.no:/home/stud/oivindoh/public_html/prosjekt/
